[package]
name = "stream-reduce"
version = "0.1.0"
authors = ["Matt Hunzinger <matthunz2@gmail.com>"]
edition = "2018"

[lib]
name = "stream_reduce"

[dependencies]
futures = "0.3.4"
pin-utils = "0.1.0-alpha.4"
